---
ID: "b4841b21-425a-4aa4-a249-cc4a4789cd47"
Parent: "9a6802d0-3c3f-41c3-8198-b836aca27cfc"
Template: "9a6802d0-3c3f-41c3-8198-b836aca27cfc"
Path: /sitecore/templates/Foundation/Teams/Team Member/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T224456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
